### ISSUE TITLE
Unable to access from website

### ISSUE THREAD

**Issue by AvKat** [jpmurray/canada-sale-tax-api#37] opened 2022-05-26 04:35 UTC
Hi. I am trying to create a website and wanted to use this api for accessing tax details.
It's not working though. There are different errors every time. Sometimes its cors, sometimes, its invalid response.

Help please

**Comment by jpmurray** [comment] 2022-06-03 10:48
I'll mark as duplicate of #36 , I'mfinally soon going to be on vacation from from, will be having to look it up !

**Closed by jpmurray** 2022-06-03 10:48 UTC

**Comment by jpmurray** [comment] 2025-02-27 01:22
@AvKat I don't know if you are still using the API, but since it's the only way I can make sure to notify people: some endpoints will be deprecated in favor of the latest version. [Please see the documentation](https://salestaxapi.ca/) !
